language: java
jdk:
  - oraclejdk8
notifications:
  email:
    on_success: always
before_deploy:
  - "git config --global user.email 'adrian.jagusch@uni-oldenburg.de'"
  - "git config --global user.name 'Adrian Jagusch'"
  - "git clone https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@$AZURE_WA_SITE.scm.azurewebsites.net:443/$AZURE_WA_SITE.git" # clone existing repository from Azure
  - "find . -name \*.* -print"
#  - "rm -rf apo/dist" # replace all the compiled files
#  - "mv dist apo/dist"
#  - "cd apo"
#  - "echo \"`date +%s`\" > date.txt" # force Azure to push the directory even if nothing changed, so that the tests can succeed
#  - "git add *"
#  - "git commit -a -m 'Push to Azure'"
#  - "git push" # push everything to the azure sever
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
